'use strict';
const vscode = require('vscode');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
exports.run = async () => {
  const extension = vscode.extensions.getExtension('t-code-demo.t-code');
  assert.ok(extension, 'Extension is installed in the test host');
  const api = await extension.activate();
  const root = vscode.workspace.workspaceFolders[0].uri.fsPath;
  assert.equal(api.state().stage, 0);
  await vscode.commands.executeCommand('tCode.focus');
  await api.showPreview();
  await Promise.all([api.submit('Any first prompt'), api.submit('Duplicate while busy')]);
  assert.equal(api.state().stage, 1);
  assert.equal(api.state().messages.filter(m => m.role === 'user').length, 1);
  const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(root, 'styles.css')));
  const edit = new vscode.WorkspaceEdit(); edit.insert(doc.uri, new vscode.Position(0, 0), '/* unsaved */');
  await vscode.workspace.applyEdit(edit);
  await assert.rejects(() => api.submit('Second'), /Save or revert/);
  await vscode.window.showTextDocument(doc);
  await vscode.commands.executeCommand('workbench.action.files.revert');
  await api.submit('Any second prompt');
  assert.equal(api.state().stage, 2);
  assert.match(fs.readFileSync(path.join(root, 'app.js'), 'utf8'), /mountMenu/);
  await assert.rejects(() => api.submit('Third'), /Both tickets/);
  const diff = await vscode.workspace.openTextDocument(vscode.Uri.parse('t-code-snapshot:/1/index.html'));
  assert.match(diff.getText(), /drink-card/);
  require('../src/demo').reset(root);
  assert.equal(api.state().stage, 0);
  assert.equal(api.state().messages.length, 0);
  await api.submit('Replay');
  assert.equal(api.state().stage, 1);
  console.log('Extension Host integration passed: activate, preview, duplicate guard, dirty editor guard, tickets, diff, reset, replay.');
};
